name: Pull Requests

on:
  pull_request:

jobs:
  pull-request:
    name: Pull Requests
    strategy:
      fail-fast: false
      matrix:
        rock-path:
          - litmuschaos-authserver
          - litmuschaos-event-tracker
          - litmuschaos-exporter
          - litmuschaos-frontend
          - litmuschaos-operator
          - litmuschaos-runner
          - litmuschaos-server
          - litmuschaos-subscriber
    uses: canonical/observability/.github/workflows/rock-pull-request.yaml@v2
    with:
      rock-path: ${{ matrix.rock-path }}
