name: Update rock

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update:
    name: Update rock
    strategy:
      fail-fast: false
      matrix:
        rocks:
          - rock-path: litmuschaos-exporter
            source-repo: litmuschaos/chaos-exporter
          - rock-path: litmuschaos-operator
            source-repo: litmuschaos/chaos-operator
          - rock-path: litmuschaos-runner
            source-repo: litmuschaos/chaos-runner
          - rock-path: litmuschaos-event-tracker
            source-repo: litmuschaos/litmus
          - rock-path: litmuschaos-subscriber
            source-repo: litmuschaos/litmus
    uses: canonical/observability/.github/workflows/rock-update.yaml@main
    with:
      rock-path: ${{ matrix.rocks.rock-path }}
      source-repo: ${{ matrix.rocks.source-repo }} 
