name: Update rock

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update:
    name: Update rock
    strategy:
      fail-fast: false
      matrix:
        rocks:
          - rock-path: litmuschaos-authserver
          - rock-path: litmuschaos-event-tracker
          - rock-path: litmuschaos-exporter
          - rock-path: litmuschaos-frontend
          - rock-path: litmuschaos-operator
          - rock-path: litmuschaos-runner
          - rock-path: litmuschaos-server
          - rock-path: litmuschaos-subscriber
    uses: canonical/observability/.github/workflows/rock-update.yaml@v2
    with:
      rock-path: ${{ matrix.rocks.rock-path }}
