name: Update rock

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update:
    name: Update rock
    strategy:
      fail-fast: false
      matrix:
        rocks:
          - rock-path: chaos-exporter
            source-repo: litmuschaos/chaos-exporter
          - rock-path: chaos-operator
            source-repo: litmuschaos/chaos-operator
    uses: canonical/observability/.github/workflows/rock-update.yaml@main
    with:
      rock-path: ${{ matrix.rocks.rock-path }}
      source-repo: ${{ matrix.rocks.source-repo }} 
